spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  datasource:
    username : sitamvan
    password : "01111997"
    url : jdbc:postgresql://localhost:5432/camunda_example
    driver-class-name: org.postgresql.Driver